version: '2'
networks:
  al_bridge:
    driver: bridge

services:
  al_login_server:
    build:
      context: "."
      dockerfile: Dockerfile
    image: al_login_server:0.7
    container_name: al_login_server
    networks:
      - "al_bridge"
    ports:
      - 2107:2107

  al_login_db:
    image: mysql:latest
    container_name: al_login_db
    ports:
      - 3306:3306
    networks:
      - "al_bridge"
    environment:
      MYSQL_USER: aion
      MYSQL_PASSWORD: aion
      MYSQL_DATABASE: al_server_ls
      MYSQL_ROOT_PASSWORD: aion
    volumes:
      - /srv/al_login_server/mysql:/var/lib/mysql

